# Site settings
title: Rocket
description: Resume & Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rocket
user_description: I am a software engineer that is still trying to learn how to build a website as a portfolio!
user_title: Software Engineer
email: tlprocket@email.com
twitter_username: tlprocket
instagram_username: tlprocket
facebook_username: tlprocket
linkedin_username: tlprocket
github_username:  tlprocket
medium_username: tlprocket
medium_url: tlprocket
gplus_username:  tlprocket

exclude: ['package.json', 'src', 'node_modules', 'vendor']

